### ISSUE TITLE
Error "name 'gender' is not defined"

### ISSUE THREAD

**Issue by donsergiobejarano** [liuhh02/food-waste-bot#1]
Hi, I´m testing the code but I got a error when I debug the code... 

Exception has ocurred: NameError
name 'gender' is not defined

I have python-telegram-bot and google maps latest version... and python 3.7...

Where could be the error?

Thanks!!

**Comment by liuhh02** [comment]
@donsergiobejarano Good catch! I have updated the bot.py file, please get the new file and run the code again. It should work now.
